server.port: 8081

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json

spring.config.activate.on-profile: docker

---
spring.config.activate.on-profile: docker
spring.rabbitmq.host: rabbitmq